icon: &icon  Material Design Icons:style=Regular:pixelsize=18
tags: &tags Material Design Icons:style=Regular:pixelsize=23
bar:
  height: 36
  location: top
  layer: bottom
  spacing: 4
  font: Proxima Nova:size=17.6
  left-margin: 6
  right-margin: 16
  foreground: F1F1F1FF
  background: 11111100
  
  left:
    - river:
        anchors:
          - base: &river_base
              margin: 6
              tag: id 
              values:
                1: {string: {text: 󰛄 , font: *tags}}  
                2: {string: {text: 󱀡 , font: *tags}}  
                3: {string: {text: 󰓇 , font: *tags}}  
                4: {string: {text: 󰎭 , font: *tags}}  
                5: {string: {text: 󰎱 , font: *tags}}  
                6: {string: {text: 󰎳 , font: *tags}}  
                7: {string: {text: 󰎶 , font: *tags}}  
                8: {string: {text: 󰎹 , font: *tags}}  
                9: {string: {text: 󰎼 , font: *tags}}  
                10: {string: {text: 󰽽, font: *tags}}  
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            tag: state
            values:
              urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              focused:
                map:
                  <<: *river_base
                  foreground: ffffffff
              visible:
                map:
                  tag: occupied
                  values:
                    false: {map: {<<: *river_base}}
                    true: {map: {<<: *river_base}}
              unfocused:
                map:
                  <<: *river_base
              invisible:
                map:
                  tag: occupied
                  values:
                    false: {empty: {}}
                    true: {map: {<<: *river_base}}
  center:
    - clock:
        time-format: "%I:%M"
        date-format: "%a %d"
        content:
          - string: {text: "{time} {date}"}
  right:
    - script:
        path: /home/missu/.local/bin/mails.sh
        args: []
        content: {string: {text: "{count}", font: *icon}}

    - network:
          name: wlan0
          content:
            map:
              tag: state
              values:
                down: {string: {text: 󰤭, font: *icon}}
                up:
                  ramp:
                    tag: signal
                    items:
                      - string: {text: 󰤟, font: *icon}
                      - string: {text: 󰤢, font: *icon}
                      - string: {text: 󰤥, font: *icon}
                      - string: {text: 󰤨, font: *icon}
    - alsa:
        card: hw:PCH
        mixer: Master
        content:
          map:
            tag: online
            values:
              false: {string: {text: X, font: *icon, foreground: ff0000ff}}
              true:
                map:
                  # on-click: /bin/sh -c "amixer -q sset Speaker unmute && amixer -q sset Headphone unmute && amixer -q sset Master toggle"
                  tag: muted
                  values:
                    true: {string: {text: 󰖁, font: *icon, foreground: ffffff66}}
                    false:
                      ramp:
                        tag: volume
                        items:
                          - string: {text: 󰕿, font: *icon}
                          - string: {text: 󰖀, font: *icon}
                          - string: {text: 󰕾, font: *icon}
    - battery:
        name: BAT1
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: "󰂃{capacity}%", foreground: ffa600ff,font: *icon}
                      - string: {text: "󰂃{capacity}%", foreground: ffa600ff,font: *icon}
                      - string: {text: 󰁼, font: *icon}
                      - string: {text: 󰁽, font: *icon}
                      - string: {text: 󰁾, font: *icon}
                      - string: {text: 󰁿, font: *icon}
                      - string: {text: 󰂀, font: *icon}
                      - string: {text: 󰂁, font: *icon}
                      - string: {text: 󰂂, font: *icon}
                      - string: {text: 󰁹, foreground: 00ff00ff, font: *icon}
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging:
                - string: {text: 󰂄, foreground: 00ff00ff, font: *icon}
                - string: {text: "{capacity}%"}
              full:
                - string: {text: 󱟢, foreground: 00ff00ff, font: *icon}
              # not charging:
              #   - ramp:
              #       tag: capacity
              #       items:
              #         - string: {text:  , foreground: ff0000ff, font: *icon}
              #         - string: {text:  , foreground: ffa600ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #         - string: {text:  , foreground: 00ff00ff, font: *icon}
              #   - string: {text: "{capacity}%"}
