icon: &icon  Material Design Icons:style=Regular:pixelsize=18
tags: &tags Material Design Icons:style=Regular:pixelsize=23
bar:
 height: 36
 location: top
 layer: bottom
 spacing: 4
 font: Proxima Nova:size=17.3
 left-margin: 6
 right-margin: 16
 foreground: F1F1F1FF
 background: 11111100
 
 left:
   - river:
       anchors:
        - base: &river_base
           margin: 6
           conditions:
            id == 1: {string: {text: 󰛄 , font: *tags}}  
            id == 2: {string: {text: 󰎧 , font: *tags}}  
            id == 3: {string: {text: 󰎪 , font: *tags}}  
            id == 4: {string: {text: 󰎭 , font: *tags}}  
            id == 5: {string: {text: 󰎱 , font: *tags}}  
            id == 6: {string: {text: 󰎳 , font: *tags}}  
            id == 7: {string: {text: 󰎶 , font: *tags}}  
            id == 8: {string: {text: 󰎹 , font: *tags}}  
            id == 9: {string: {text: 󰎼 , font: *tags}}  
            id == 10: {string: {text: 󰽽, font: *tags}}  
       content:
        map:
          on-click:
            left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
            right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
            middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
          conditions:
            state == urgent:
              map:
                <<: *river_base
                deco: {background: {color: D08770ff}}
            state == focused:
              map:
                <<: *river_base
                foreground: ffffffff
            state == visible:
              map:
                conditions:
                  ~occupied: {map: {<<: *river_base}}
                  occupied: {map: {<<: *river_base}}
            state == unfocused:
              map:
                <<: *river_base
            state == invisible:
              map:
                conditions:
                  ~occupied: {empty: {}}
                  occupied: {map: {<<: *river_base}}
 center:
   - clock:
       time-format: "%I:%M"
       date-format: "%a %d"
       content:
         - string: {text: "{time} {date}"}
 right:
   - script:
       path: /home/missu/.config/yambar/scripts/_yambar_caffiene
       content:  {string: {text: "{CAFFIENE}", font: *icon}}
   - script:
       path: /home/missu/.config/yambar/scripts/_yambar_mail
       content:  {string: {text: "{COUNT}", font: *icon}}
   - network:
         name: wlan0
         content:
           map:
             conditions:
               state == down: {string: {text: 󰤭, font: *icon}}
               state == up:
                 ramp:
                   tag: signal
                   items:
                     # - string: {text: 󰤟, font: *icon}
                     - string: {text: 󰤢, font: *icon}
                     - string: {text: 󰤥, font: *icon}
                     - string: {text: 󰤨, font: *icon}
   - alsa:
       card: hw:PCH
       mixer: Master
       content:
         map:
           conditions:
             ~online: {string: {text: X, font: *icon, foreground: ff0000ff}}
             online:
               map:
                 # on-click: /bin/sh -c "amixer -q sset Speaker unmute && amixer -q sset Headphone unmute && amixer -q sset Master toggle"
                 conditions:
                   muted: {string: {text: 󰖁, font: *icon }}
                   ~muted:
                     ramp:
                       tag: volume
                       items:
                         - string: {text: 󰖀, font: *icon}
                         - string: {text: 󰖀, font: *icon}
                         - string: {text: 󰕾, font: *icon}
   - battery:
       name: BAT1
       poll-interval: 20
       anchors:
         discharging: &discharging
           list:
             items:
               - ramp:
                   tag: capacity
                   items:
                     - string: {text: "󰂃{capacity}%", foreground: ffa600ff,font: *icon}
                     - string: {text: "󰂃{capacity}%", foreground: ffa600ff,font: *icon}
                     - string: {text: 󰁼, font: *icon}
                     - string: {text: 󰁽, font: *icon}
                     - string: {text: 󰁾, font: *icon}
                     - string: {text: 󰁿, font: *icon}
                     - string: {text: 󰂀, font: *icon}
                     - string: {text: 󰂁, font: *icon}
                     - string: {text: 󰂂, font: *icon}
                     - string: {text: 󰁹, font: *icon}
       content:
         map:
           conditions:
             state == unknown:
               <<: *discharging
             state == discharging:
               <<: *discharging
             state == charging:
               - string: {text: 󰂄, foreground: 00ff00ff, font: *icon}
               - string: {text: "{capacity}%"}
             state == full:
               - string: {text: 󱟢, foreground: 00ff00ff, font: *icon}

