#!/usr/bin/bash

INTERVAL=20

printf -- '%s\n' "COUNT|string|"
printf -- '%s\n' ""

while true
do
  if $(iw dev wlan0 info | grep -q ssid);then
    wget -q --spider 1.1.1.1

    if ! ([ $? -eq 0 ]); then
      continue
    fi
  fi
  # COUNT=$(heroku run getcount.sh -a emailcount &> /dev/null)
  # COUNT=$(_s-unread-count -u mizzunet -p $HYDROXIDE_BRIDGE_PASS -S 127.0.0.1 -P 1143)
  COUNT=$(sqlite3 ~/.local/share/geary/account_02/geary.db 'SELECT unread_count FROM FolderTable WHERE id=15')
  
  if test $COUNT -gt 0;then
    COUNT="󰁥 $COUNT"
  else
    COUNT=""
  fi

  printf -- '%s\n' "COUNT|string|${COUNT}"
  printf -- '%s\n' ""

 sleep $INTERVAL
done
