#!/usr/bin/bash

INTERVAL=60

printf -- '%s\n' "COUNT|string|"
printf -- '%s\n' ""

while true
do
  if $(iw dev wlan0 info | grep -q ssid);then
    wget -q --spider 1.1.1.1

    if ! ([ $? -eq 0 ]); then
      # COUNT=$(heroku run ./getcount.sh -a emailcount &> /dev/null)
    # else
      continue
    fi
  fi
  # if ! (pidof hydroxide> /dev/null);then
  #     sleep $INTERVAL
  #     continue
  # fi

  # COUNT=$(heroku run ./getcount.sh -a emailcount)
  COUNT=$(/home/missu/.git/mine/emailcount/getcount.sh)

  printf -- '%s\n' "COUNT|string|${COUNT}"
  printf -- '%s\n' ""

#  sleep $INTERVAL
done
