#!/usr/bin/env bash
# Script to change brightness level by brillo with animation. Also send notification

if (( $(bc <<<"$(brillo) < 5.0") ));then
	up=2
	down=2
else
	up=4
	down=8
fi

case $1 in
	up)
		brillo -q -u 150000 -A $up
		;;
	down)
		brillo -q -u 150000 -U $down
		;;
esac

notify-send -u low -a control -t 1000 \
	-h int:value:$(brillo) \
	"Brightness" 

