#!/bin/bash
# Starts watching clipboard and shows list of items by bemenu
PICKER=bemenu
ARGS='-l 40 -n -b -i --wrap 
	--fn "JetBrains Mono 10" \
	--hb #ffffff \
	--hf #00000  \
	--nb #000000 \
	--nf #ffffff'

case $1 in
	history)
	clipman pick -t $PICKER --tool-args="$ARGS"
	;;
	watcher)
	wl-paste -t text --watch clipman store 
	;;
esac

