#!/bin/bash
# playwithmpv - script to copy Firefox's current page URL by Vimium-c and play the URL with mpv

SPEED=2.3
FORMAT='139+133'
MPV_ARGS="--config-dir=/home/missu/.config/mpv --script=/etc/mpv/scripts/mpris.so --pause --speed=$SPEED --save-position-on-quit --hwdec=auto --gpu-context=wayland --ytdl-format=$FORMAT"
URL=$(wl-paste)
# URL=$1
if [[ $URL == https://* && $URL != *channel* ]]; then # check if the copied item is https link and doesn't include 'channel'
  if ! $(grep -q $URL /tmp/playwithmpv); then         # check if already played video
    echo "$URL" >> /tmp/playwithmpv                   # store the url temporarily for checking if already played
    notify-send -u low -t 3000 -a control \
        playwithmpv "$URL"         
    mpv $URL $MPV_ARGS || notify-send -u low -t 1000 playwithmpv 'Failed to recognize file format' 
  else
    notify-send -t 1000 -u low -a control \
    playwithmpv 'Video has already been played' 
  fi
else                                                 # not a valid url
  notify-send -t 1000 -u low -a control \
    playwithmpv 'Not a valid video URL' 
fi
