#!/bin/bash
action="$@"
current="$(light -G)"
threshold=5
lower=0.2
higher=6

case $action in
	up)
        if (( $(bc <<<"$current < $threshold") ));  then light -A $lower;else light -A $higher; fi
		;;
	down)
        if (( $(bc <<<"$current < $threshold+5") ));  then light -U $lower ;else light -U $higher; fi
		;;		

	esac

current="$(light -G)"
notify-send -u low  -h int:value:$current "Brightness󰃟" -t 1000 

