#!/bin/bash
action="$@"
current="$(light)"


case $action in
	#up)
		#if [ $current -lt 10 ]; then  light -A 1;else light -A 5; fi
		#;;
	down)
		if [ $current -lt 10 ]; then  light -U 1;else light -U 5; fi
		;;		

	esac
	notify-send -u low  -h int:value:$(light) "Brightness󰃟" -t 1000 

