#!/usr/bin/bash

INTERVAL=30

printf -- '%s\n' "COUNT|string|"
printf -- '%s\n' ""

while true;do
  if ! (pidof hydroxide> /dev/null);then
      sleep $INTERVAL
      continue
  fi

  COUNT=$(unread-count -u mizzunet -p $HYDROXIDE_BRIDGE_PASS -S 127.0.0.1 -P 1143)

  printf -- '%s\n' "COUNT|string|${COUNT}"
  printf -- '%s\n' ""

  sleep $INTERVAL
done
